[project]
name = "amazigh-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chain>=1.0",
    "datasets==3.6.0",
    "montreal-forced-aligner>=3.3.8",
    "pybind11>=3.0.1",
]
